tabWidth: 2
useTabs: false
printWidth: 100
trailingComma: "all"
semi: true
importOrder: ["^@/", "^[./]"]
importOrderSeparation: true
plugins:
  ["prettier-plugin-astro", "prettier-plugin-tailwindcss", "@trivago/prettier-plugin-sort-imports"]
